//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public int ProcesoId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string Nota { get; set; }
        public int EstadoTicketId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoTicket EstadoTicket { get; set; }
        public virtual Proceso Proceso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
